# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f8bd385e56000ab4a7dfd390707862706698942d29003257e60c7c99aef6c9b973f0925e0cd6f0b6d743b1f48933769045300a594dc13c7887debc8f46c10e6

test:
  secret_key_base: 179db27f6add0e1b5acb2fa1ba63b51e4eabf6c01d6519c511c09600749f0549f520d1d0025da2459ad497858014e1a5ed7bda9fa0b6cec25179de4fb7e41b82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
